version: "3.4"
services:
  seleniumServer:
    image: "selenium/standalone-chrome:latest"
    ports:
      - "4444:4444"
  web:
    build: .
    depends_on:
      - seleniumServer
    command:
      [
        "/opt/selenium-example/wait-for-it.sh",
        "seleniumServer:4444",
        "--",
        "bin/selenium-example-exe",
        "--host=seleniumServer",
      ]
