version: "3.4"
services:
  seleniumServer:
    image: "selenium/standalone-chrome:3.141.59-selenium"
    ports:
      - 4444:4444
  web:
    build: .
    depends_on:
      - seleniumServer
    command:
      [
        "/opt/haskell-selenium-boilerplate/wait-for-it.sh",
        "seleniumServer:4444",
        "--",
        "bin/haskell-selenium-boilerplate-exe",
        "--host=seleniumServer",
      ]
