library:
  source-dirs: src
copyright: 2019 Max Sun
maintainer: maxlouiesun@gmail.com
dependencies:
- time
- clock
- formatting
- exceptions >= 0.10.3
- cmdargs >= 0.10.20
- array >= 0.5.3.0
- base >= 4.7 && < 5
- aeson >= 0.6.2.0
- webdriver <= 0.9.0.1
- text  <= 1.2.3.0
- naturals >= 0.2.0.2
- http-types >= 0.12.3
- dlist >= 0.8.0.7
- mtl >= 2.2.2
- datetime-sb >= 0.2.4
- containers >= 0.6.0.1
- async >= 2.2.2
- stm >= 2.5.0.0
- ttrie >= 0.1.2.1
- transformers >= 0.5.6.2
- extra >= 0.3.1
- bytestring >= 0.10.8.2
name: haskell-selenium-boilerplate
version: 0.1.0.0
extra-source-files:
- README.md
author: Max Sun
github: maxsun/haskell-selenium-boilerplate
license: BSD3
executables:
  haskell-selenium-boilerplate-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-selenium-boilerplate
description: Please see the README on GitHub at <https://github.com/maxsun/haskell-selenium-boilerplate#readme>
