library:
  source-dirs: src
copyright: 2019 Max Sun
maintainer: maxlouiesun@gmail.com
dependencies:
- exceptions >= 0.10.3
- cmdargs >= 0.10.20
- array >= 0.5.3.0
- base >= 4.7 && < 5
- aeson >= 0.6.2.0
- webdriver <= 0.9.0.1
- text  <= 1.2.3.0
- http-types >= 0.12.3
name: haskell-selenium-boilerplate
version: 0.1.0.0
extra-source-files:
- README.md
author: Max Sun
github: maxsun/haskell-selenium-boilerplate
license: BSD3
executables:
  haskell-selenium-boilerplate-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-selenium-boilerplate
description: Please see the README on GitHub at <https://github.com/maxsun/haskell-selenium-boilerplate#readme>
